project:
  type: website
  output-dir: docs

website:
  title: "Reproducibility in Transportation Research: A Hands-on Tutorial 2.0 – Reproducible Manuscripts"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: "About"
        href: about.qmd
      - text: "Schedule"
        href: schedule.qmd
      - text: "Team"
        href: organisers.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

