---
title: "Schedule"
format: html
---

## Tutorial Session Plan

#### Details

-   When: 8:30-12:30 (Brisbane local time) \| Tuesday, November 18, 2024 (<https://ieee-itsc.org/2025/program/workshops-and-tutorials/>)

-   Where: Room Gold Coast \| the *Star Grand* \| *Broadbeach* \| *Gold Coast*.

-   👉 Participants should **bring laptops** to participate in hands-on sessions **with installed required software**, including

    -   [RStudio](https://posit.co/download/rstudio-desktop/) (by default, [Quarto](https://quarto.org/) will be automatically installed when you install the latest version of RStudio)

    -   A [Github](https://github.com/) account (see [tutorial](https://swcarpentry.github.io/git-novice/#creating-a-github-account))

    -   [Anaconda Python](https://www.anaconda.com/download/success) and Jupyter

    -   [Overleaf](https://www.overleaf.com/)

**Please note:** A little bit of coding experience with RStudio or Python will be more than enough for this tutorial. Even if you’ve never written a line of code in your life, don’t stress — you’ll still be able to follow along with most of the activities. This tutorial is about making your manuscript reproducible, **not about showing off your coding superpowers** (though hey, you might unlock a few along the way!).

[***Opening remarks (Professor Cathy Wu, MIT) & Pre-tutorial survey (8:30am - 8:40am)***]{.underline}

[***Session 1: Introduction to Reproducible Research***]{.underline} ***(8:40am-9:40am)\
*****Presentation 1:** Making your manuscript reproducible: an Editor’s perspective by Professor David Levinson (USYD)

**Presentation 2:** Introduction to reproducible research and reproducible manuscript by Professor Zuduo Zheng (UQ)

**Activity 1:** Is your most recent manuscript reproducible?\

***COFFEE BREAK (9:40am-10:00am)***

[***Session 2: Reproducibility for research collaboration***]{.underline} ***(10:00am-11:00am)\
*****Presentation 3:** Tools for practicing reproducible research collaboration by Professor Zuduo Zheng & Dr Saeed Mohammadian (UQ)\
**Activity 2:** Computer exercise

***COFFEE BREAK (11:00 am-11:30am)***

[***Session 3: Reproducibility for publication: How to make your next manuscript reproducible?***]{.underline} ***(11:30am-12:30 pm)***\
**Demonstration 1:** Making reproducible manuscripts using RStudio and Quarto By Mr Hongbo Zhao (UQ)\
**Demonstration 2:** Making reproducible manuscripts using Python, Overleaf and Code Ocean by Dr Saeed Mohammadian (UQ)\
**Activity 3:** Make your most recent manuscript reproducible**\
Q&A and & Post-tutorial survey**

***OPTIONAL LUNCH (12:30 pm-1:30pm):*** Join us for a collaborative working lunch to build and strengthen the community dedicated to Reproducible Research in Transportation.

**Contact person:** Zuduo Zheng ([zuduo.zheng\@uq.edu.edu](mailto:zuduo.zheng@uq.edu.edu))
